development: &common_settings
  publish_url: 'http://stesaam0.corp.w3data.com:4567/publish'
  redis:
    service_port: 6379
    default_timeout: 30
    service_host: 'localhost'

test:
  <<: *common_settings
  publish_url: 'http://test.com/publish'

production:
  publish_url: http://production.com/publish